{% set version = "2023.11.1" %}

package:
  name: nebari-dask
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - dask ==2023.11.0
    - distributed ==2023.11.0
    - dask-gateway ==2023.9.0

test:
  imports:
    - dask

about:
  home: https://github.com/nebari-dev
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Nebari dask dependencies."

extra:
  recipe-maintainers:
    - viniciusdc
    - iameskild
    - trallard
    - dcmcand
